apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: tun-device-plugin
    app.kubernetes.io/managed-by: kustomize
  name: plugin-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: plugin-role
subjects:
  - kind: ServiceAccount
    name: plugin
    namespace: system
