name: tests

on:
  pull_request:
    branches: [ "*" ]
  push:
    branches:
      - "main"

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
      - run: |
          go install github.com/linuxkit/linuxkit/src/cmd/linuxkit@latest
      - run: |
          make test
      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  e2e:
    runs-on: ubuntu-latest
    needs:
      - unit
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
      - run: |
          make \
            cluster \
            docker-build docker-push \
            deploy
      - run: |
          make \
            test-e2e
